### ISSUE TITLE
Trying to update and get an error

### ISSUE THREAD

**Issue by iamgiannisx** [razonyang/hugo-theme-bootstrap#581] opened 2022-06-28 15:26 UTC
I am trying to update to v1 and i get the following error when i run the command 
`hugo mod get github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.0`

`Error: failed to get ["-d" "github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.0"]: binary with name "go" not found`

**Comment by iamgiannisx** [comment] 2022-06-28 15:45
Checked and installed, now I am getting the following 
`go: can't request version "v1.0.0-alpha.0" of the main module (github.com/razonyang/hugo-theme-bootstrap)
Error: failed to get ["-d" "github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.0"]: failed to execute 'go [get -d github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.0]': failed to execute binary "go" with args [get -d github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.0]: go: can't request version "v1.0.0-alpha.0" of the main module (github.com/razonyang/hugo-theme-bootstrap)`

**Comment by razonyang** [comment] 2022-06-28 15:58
Cloud you please provide the `hugo` and `go` version? I'll try to reproduce this issue.

- `hugo version`
- `go version`

**Comment by iamgiannisx** [comment] 2022-06-28 16:07
![Screenshot 2022-06-28 at 19 07 10](https://user-images.githubusercontent.com/33219224/176227804-ee3edb26-6d1b-44c9-a217-68b54f3e4049.png)

**Comment by razonyang** [comment] 2022-06-28 16:42
Hmm, tried in two machines, but can't reproduce it with `hugo-v0.101` and `go1.18.3`. Currently, I have no clue how to fix it.

You can ask for help on [Hugo forum](https://discourse.gohugo.io/).

**Comment by razonyang** [comment] 2022-07-01 04:21
Hi @iamgiannisx, does the issue still exists?

**Comment by iamgiannisx** [comment] 2022-07-02 09:19
I updated through another machine (Macbook with Intel processor) I suppose that there some issues with Mac M1.

**Comment by razonyang** [comment] 2022-07-02 09:48
Ok, I'm going to close this issue.

**Closed by razonyang** 2022-07-02 09:48 UTC
