### ISSUE TITLE
Twitter integration is crashing the building

### ISSUE THREAD

**Issue by nunomazer** [razonyang/hugo-theme-bootstrap#970] opened 2023-07-28 12:00 UTC
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

When I call hugo for build my site the following error message is showed:

ERROR Failed to get JSON resource "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2Fnunomazer%2Fstatus%2F1289558331888209920": Get "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2Fnunomazer%2Fstatus%2F1289558331888209920": dial tcp 104.244.42.67:443: i/o timeout

Error: error building site: render: failed to render pages: render of "page" failed: "/tmp/hugo_cache_mazer/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.0.2/layouts/_default/baseof.html:12:8": execute of template failed: template: _default/single.html:12:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: partial "head.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.

### Steps to reproduce

Just call hugo

### Expected behavior

To build the site wtihout crash

### What operating system(s) are you seeing the problem on?

Linux

### What version of theme are you using?

1.0.2

### What version of Hugo are you using?

v0.115.4-

**Comment by razonyang** [comment] 2023-07-28 12:03
> dial tcp 104.244.42.67:443: i/o timeout

It looks like a network issue, have you test it in other network environment? Or you can share your repo or code snippet for reproducing it?

**Comment by nunomazer** [comment] 2023-07-28 12:19
I have sent you an invite to the repo. 

Well it could be but is stranger because all other network dependent actions were ok.

But I have to say, until 10 minutes ago since yesterday the problem didn't change, I just tried again now and the build was done

**Comment by razonyang** [comment] 2023-07-28 12:39
I tested your repo via GitHub workflow, seems to work now, according to the error logs, I believe it's a network issue (it may be caused by the Twitter side or the build env side), not related to Hugo and this theme, so I'm closing it for now.

**Closed by razonyang** 2023-07-28 12:39 UTC
Labels: bug
