### ISSUE TITLE
Avoid flickering on dark mode on first page load

### ISSUE THREAD

**Issue by Rubonnek** [razonyang/hugo-theme-bootstrap#680] opened 2022-08-27 12:31 UTC
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

When enabling dark mode,  the page theme will flicker from light mode to dark mode on the first page load.

### Steps to reproduce

1. Enable dark mode.
2. Clear website cache in your browser.
3. Load page. The flickering might not be visible at all sometimes.

### Expected behavior

No flickering at all.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

v1.0.0-alpha.8

### What version of Hugo are you using?

hugo v0.101.0+extended linux/amd64 BuildDate=unknown

### What version of Node.js are you using?

v18.8.0

### What version of Git are you using?

git version 2.37.2

### Additional context

This issue does not seem to happen on subsequent page reloads, as noted in #668.

This issue only seems to happen when there is no cache and the page has loaded for the first time.

**Comment by razonyang** [comment] 2022-08-27 13:38
Cloud not reproduce this issue. As the animation image shown, I force refresh the page without cache(`CTRL`+`F5`).
Could you please provide a screenshot to show how to reproduce it?
There are some tools for doing that: Awesome screenshot and screen recorder(Chrome extension) or ScreenToGif(may not available in Linux platforms).
![flickering](https://user-images.githubusercontent.com/17720932/187032469-c01747a0-f5b7-4f26-a744-5ba557a720e7.gif)

**Comment by Rubonnek** [comment] 2022-08-27 14:49
Hmm... it seems harder to reproduce with the documentation site. Feels easier able to reproduce the issue with the skeleton -- all I did was enable dark mode and set the palette to blue.

Here's [a recording](https://profiler.firefox.com/public/kf6d06wf9c26te9npg645f5gms3h9mcq71vt26g/calltree/?globalTrackOrder=60w5&hiddenGlobalTracks=1w4&hiddenLocalTracksByPid=66620-0w6~66878-0~66904-0~66956-0~67056-01&implementation=js&thread=d&v=7) with Firefox Developer Edition. I'm also able to reproduce with Chromium as well.

On the top section, if you scroll up you'll see the screenshots of the page loading and the light-to-dark theme flicker is visible as well:
![flicker](https://user-images.githubusercontent.com/8337880/187035374-66aabc63-68fe-4e32-8768-2903ff14f52d.png)

**Comment by razonyang** [comment] 2022-08-27 15:29
Does this issue exist in https://hbs-skeleton.netlify.app/ as well?
I used the same tool(Firefox -> Performance -> Start recording) for testing that site, but didn't reproduce it.

**Comment by Rubonnek** [comment] 2022-08-27 15:32
Yup. It flickers as well -- [here's the recording](https://profiler.firefox.com/public/8f2pmhsg6c4rhwngtkayxb67nafs5hd8bg68jgg/calltree/?globalTrackOrder=no0wm&hiddenGlobalTracks=1wkm&hiddenLocalTracksByPid=66620-0w6~66878-0~73557-0~69806-0~69801-0~71423-0~73302-0~66956-0~70059-01~72218-0~70444-0~72289-0~72368-0~66904-0~72463-0~70143-0~73420-0~69882-0~72516-0~73126-01~69822-01~69958-0w2&implementation=js&thread=u&v=7).

**Comment by Rubonnek** [comment] 2022-08-27 15:35
By the way, the issue doesn't always happen. Maybe there's a race condition somewhere in the rendering pipeline?

For whatever reason, the easiest way I'm able to reproduce is like this:

- Visit the site https://hbs-skeleton.netlify.app/ with Firefox in regular mode.
- Ensure no other private browsing windows are opened.
- Open a private browsing window.
- Open the developer tools and start recording
- Paste https://hbs-skeleton.netlify.app/ in the URL bar and quickly press enter.

I'm not sure why doing testing it like that helps trigger the issue.

**Comment by razonyang** [comment] 2022-08-27 15:37
Btw, what version of your browser(Firefox and Chrome)? I'll try to reproduce it using Arch OS instead of Windows.

**Comment by Rubonnek** [comment] 2022-08-27 15:44
I'm using Arch Linux as well. I'm using the latest Firefox Devloper Edition and Chromium browsers from the official repositores,
```bash
sudo pacman -S firefox-developer-edition chromium
```

Their versions are:
- Firefox Developer Edition: 105.0b3 (64-bit)
- Chromium: Version 104.0.5112.101 (Official Build) Arch Linux (64-bit)

**Comment by Natenom** [comment] 2022-08-27 23:14
Not sure if this could be related to a problem on my blog: Enabling the dark mode the background is always white (as seen in the very small screenshot of the recorded session).

See https://blog.natenom.com/

**Comment by razonyang** [comment] 2022-08-28 02:22
> 

I guess it's not, please upgrade to the latest change of master branch, it looks like the issue is about PurgeCSS removes styles of `data-bs-theme` attribute which has been fixed by 75e0e86
https://github.com/razonyang/hugo-theme-bootstrap/blob/7c046a2c832b0a39e3196fd55bfcfe8fe46bedc8/purgecss.config.js#L38

**Comment by razonyang** [comment] 2022-08-28 03:53
@Rubonnek I'm still can't reproduce it, I try it multiple times. I also check this with private window, but with no luck.

Chrome(104):
[Screencast 2022-08-28 11:41:06.webm](https://user-images.githubusercontent.com/17720932/187056371-dcdfb71f-61e4-4207-9136-fb0cf261af93.webm)

Firefox(104):
[Screencast 2022-08-28 11:50:59.webm](https://user-images.githubusercontent.com/17720932/187056539-941d8908-6f0e-40e7-b7b3-4a5685d3b40a.webm)
https://profiler.firefox.com/from-browser/calltree/?globalTrackOrder=80w7&hiddenGlobalTracks=1w6&hiddenLocalTracksByPid=137570-02w7&implementation=js&thread=f&v=7

**Comment by Rubonnek** [comment] 2022-08-28 13:15
@razonyang Hmm.... I can reproduce with Firefox(104) and Chrome(104) as well. I also see the flicker on my phone.

For the recordings below, I used the skeleton with a one line patch in the configuration:

```diff
index 9130288..2ce617d 100644
--- a/config/_default/params.yaml
+++ b/config/_default/params.yaml
@@ -33,7 +33,7 @@ palette: purple # Default palette. Optional. You'll need to clear the browser ca
 #  - teal
 #  - yellow
 
-# color: dark # light, dark or dynamic. Default to dynamic.
+color: dark # light, dark or dynamic. Default to dynamic.
 
 # fullWidth: true # Full width.
 # fixedHeader: false # Turn on/off fixed header.
```

Recordings:
- [Chrome(104).webm](https://user-images.githubusercontent.com/8337880/187075754-73e4debe-e85c-4817-b332-8d6b4d9d8742.webm)
- [Firefox(104).webm](https://user-images.githubusercontent.com/8337880/187075406-15c07b68-8dad-455c-a5c5-6a277673158d.webm) and https://share.firefox.dev/3cp3Vpw

**Comment by Rubonnek** [comment] 2022-08-28 13:28
It seems like the flicker is related to the theme partial used here:
https://github.com/razonyang/hugo-theme-bootstrap/blob/68ba4815a95d4e27e9a5ac0bd82cab5ca44ec202/layouts/partials/header/index.html#L66

If I remove that line from the partial, on the first page load the theme doesn't change to dark -- it stays in light mode (even though it was configured to be dark as shown in my previous comment). There's no flicker, but if I refresh it turns to dark mode.

**Comment by razonyang** [comment] 2022-08-28 15:02
I see, it happens on the first time loading in the case of `color=dark`. I'm working on it.

**Comment by razonyang** [comment] 2022-08-28 15:16
@Rubonnek could you please test the patch `bugfix-dark-mode-flickering` to see if there are any other issues?

Upgrade via `hugo mod get github.com/razonyang/hugo-theme-bootstrap@bugfix-dark-mode-flickering`.

**Comment by Rubonnek** [comment] 2022-08-28 15:43
@razonyang There's no flickering with that patch!

I'm not too familiar with the Javascript code yet, but I guess I should mention I see a second switch to dark mode in the console:
```
Switch to dark mode [bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js:153:15](http://localhost:1313/assets/init/bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js)
switch to palette: purple [bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js:207:15](http://localhost:1313/assets/init/bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js)
Switch to dark mode [bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js:153:15](http://localhost:1313/assets/init/bundle.min.642ef4027ee5a1891fa726505fb4f9867113d43e88632b92345105c9c53e7e0e.js)
```
I don't know if that 's important though.

**Closed** 2022-08-28 16:17 UTC
Labels: bug

**Comment by razonyang** [comment] 2022-08-28 16:19
@Rubonnek Thanks, I refactored that class, the issue should be fixed now.

**Comment by Rubonnek** [comment] 2022-08-28 16:48
@razonyang thank you!
