### ISSUE TITLE
Style sheet problems on first/initail load ?

### ISSUE THREAD

**Issue by jehoshua7** [razonyang/hugo-theme-bootstrap#213] opened 2021-09-19 03:29 UTC
If I close the browser (Firefox) all cache and history is cleared. I can then go to a site and it will load/display okay.

Yet today when I deployed the theme, and went to the site, it appears the style sheet is not loading properly. I did notice the same thing the other day with one of the demo sites for this theme.

So it is only the first/initial load, I can click on a link and it then looks okay. Please see attached screendump for an example of what is happening.
![HBS_Initial_Load](https://user-images.githubusercontent.com/33979036/133914440-7c97a79d-a429-43ff-9cad-3cbf5efae1d8.png)

**Comment by razonyang** [comment] 2021-09-22 15:25
This is probably because the CSS file is not loaded. But I have no clue to fix it, could you please provide the reproduce steps?

**Comment by jehoshua7** [comment] 2021-09-22 22:47
To reproduce the problem, as follows:

1. Close Firefox, all windows and tabs (all cache/history, cookies, etc is always auto deleted)
2. Open Firefox and go to  http://example.com 
3. The CSS is not properly loaded.

The server logs show no issues or problems, like every request returns a '200'.

If I go to https://hbs.razonyang.com/  it displays the same (style sheet issues) initially but then displays okay automatically

If I go to http://example.com and open the browser console, it shows

> 08:19:25.430 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example.com/js/bundle.min.2424c68327e09b751266797e010bd49d27a620c3c967a263f97d1c1d62848534.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

> 08:19:25.431 None of the “sha256” hashes in the integrity attribute match the content of the subresource. example.com
08:19:25.499 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example.com/css/bundle.min.584ad61bfb9121e174610ca0716e7303fbd4708cb91ca3f4b802d8d6d4745f84.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).


Browser settings maybe ?? I only have Firefox installed and don't want to install/use another browser. I did try it with a html editor (Bluegriffon) and the same problem occured.

Some searching and reading posts, found https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

It looks like I need to see if a mod to the .htaccess file will fix it ??

**Comment by razonyang** [comment] 2021-09-23 03:06
I think the http://example.com and https://example.com are treated as difference origins, so that browser blocked the remote resource. Does https://example.com works?

**Comment by jehoshua7** [comment] 2021-09-23 04:51
Yes, , it is as you say, https://example.com works , but  http://example.com has the (initial) style sheet problem

**Comment by razonyang** [comment] 2021-09-23 05:08
> Yes, , it is as you say, https://example.com works , but http://example.com has the (initial) style sheet problem

The best solution is always to redirect to HTTPS from HTTP. You can also fix it by setting `Access-Control-Allow-Origin` server header. But I don't recommend the latter.

It's a problem of server configuration, so I'm going to close this issue.

**Closed by razonyang** 2021-09-23 05:08 UTC
Labels: question

**Comment by jehoshua7** [comment] 2021-09-24 03:53
I'll add the Apache rewrite condition/rules to force HTTPS as shown at [How to Force HTTPS using .htaccess](https://linuxize.com/post/htaccess-force-https/) to .htaccess

The theme config file and the sitemap have HTTPS, so that should cover all scenarios
