### ISSUE TITLE
Search does not work anymore and no favicon

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#737] opened 2022-09-23 19:57 UTC
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

No search results and no favicon on search page.

Console:
```
bundle.min.5fa01429543d832a967be5eff5a8dcfb34c13daca3ac931d73962c86eedb89a2.js:4 unable to load search index TypeError: Cannot read properties of undefined (reading 'map')
    at bundle.min.5fa01429543d832a967be5eff5a8dcfb34c13daca3ac931d73962c86eedb89a2.js:4:17435

favicon.ico:1          GET https://blog.natenom.com/search/images/icons/favicon.ico?version=dfcb0a79d3dfae2e987614f08fc397b4 404
icon-32x32.png:1          GET https://blog.natenom.com/search/images/icons/icon-32x32.png?version=59b0400ff124f8db65c12843e44c7b62 404
icon-16x16.png:1          GET https://blog.natenom.com/search/images/icons/icon-16x16.png?version=4ca0a77ac3d1dde819ad3a7b9c232f18 404
```

See https://blog.natenom.com/

Works with theme before the search improvements were done.

### Steps to reproduce

Build.

### Expected behavior

Working search.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

5bd552923d2bd1da71fca376d763f3b93ebe9863 (HEAD -> master, origin/master, origin/HEAD) fix(search): empty the layouts.index.json for backward compatible

### What version of Hugo are you using?

hugo v0.103.0+extended linux/amd64 BuildDate=2022-09-16T20:37:28Z VendorInfo=debian:0.103.0-1

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.35.1

**Comment by razonyang** [comment] 2022-09-24 01:16
Sorry for the late reply, just woke up, those issues should be fixed now.

**Closed** 2022-09-24 01:16 UTC
Labels: bug

**Comment by Natenom** [comment] 2022-09-24 01:43
It works now in Chromium but loads endless in Firefox.

**Comment by razonyang** [comment] 2022-09-24 02:07
@Natenom seems OK, could you provide the reproduce steps, maybe I missed something.

> As the image shown, I disabled the cache.

![search](https://user-images.githubusercontent.com/17720932/192075434-02f38ea1-b3d1-4238-80f7-20b03a536b5a.gif)

**Comment by Natenom** [comment] 2022-09-25 07:10
Hmm, tried search for "open" and it is very fast, but after showing the search results the page is not usable anymore and cpu usage is 100 %.

![image](https://user-images.githubusercontent.com/385995/192132438-e2f42ccf-6a1e-476c-a37b-c9c40ed26818.png)

**Comment by Natenom** [comment] 2022-09-25 07:28
Sometimes it works, sometimes not. I tried a fresh firefox profile with no extensions. Results is the same. Search results load (sometimes) and then 100 % cpu usage.

**Comment by razonyang** [comment] 2022-09-25 07:53
@Natenom Yep, I reproduced this issue on your blog site, but could not reproduce it on a demo site that contains over 10k posts.

![image](https://user-images.githubusercontent.com/17720932/192133702-8326df69-c31f-4c98-93f0-7f4f76fd6401.png)

The issue is that the result rendering hangs a few seconds(5~15s), although partial results have been rendered.

https://share.firefox.dev/3xRKWvc

Need to reproduce it in local environment for determining the root cause of problem, I'll try to download your site's index files to emulate it.

**Comment by razonyang** [comment] 2022-09-25 08:41
Hmm, I'm unable to reproduce it in local and production environment with your search indexes.

https://razonyang.github.io/hbs-test/en/search/?q=gehwege

I found that the results are different between your site and the test site above, even they use same indexes.
Could you please provide your whole repo(repo read only access or other way) for generating the site for testing?

**Comment by Natenom** [comment] 2022-09-25 08:48
Jupp, preparing the archive currently. Will send you the link on twitter.

**Comment by Natenom** [comment] 2022-09-25 08:59
Done

**Comment by razonyang** [comment] 2022-09-26 07:38
Just for tracking, the hangs issue is caused by FontAwesome `searchPseudoElements` which took a long time to render.
Now the issue has been fixed by disabling that option.
